name: CaptureTheFlagMGI
api: [1.12.0]
author: robozeri
version: 1.0
description: Base of Capture the flag
main: CTF\Main
commands:
 ctf:
  permission: ctf.command.ctf
  description: ctf command
  usage: /ctf set|restart
